### ISSUE TITLE
Twitch emote api v3으로 변경

### ISSUE THREAD

**Issue by Lastorder-DC** [rishubil/jsassist-open-dccon#14]
[https://twitchemotes.com/apidocs](https://twitchemotes.com/apidocs)

v2 api가 deprecate되어 더이상 업데이트가 반영되지 않습니다.

**Comment by rishubil** [comment]
알려주셔서 감사합니다.
가능한 한 빠른 시일 내에 수정해야겠네요.

**Comment by rishubil** [comment]
4397a4d6d62df8b3c35f43d948ffa37b58c97ceb 에서 수정
