### ISSUE TITLE
불필요한 웹폰트 참조

### ISSUE THREAD

**Issue by Lastorder-DC** [rishubil/jsassist-open-dccon#15]
![image](https://user-images.githubusercontent.com/18280396/29498637-9c41afd6-863b-11e7-8564-8310d437a286.png)
mixed content 문제로 불러와지지 않고 있는 css 파일 있습니다

**Comment by rishubil** [comment]
해당 웹폰트는 https://github.com/rishubil/jsassist-open-dccon/blob/44e02097e1bfe3e983322754e2ed71a7edb6b6c3/source/static/jsassist/css/styles.css#L1-L6 에 정의되어 있습니다.

이 파일은 JSAssist에서 제공하는 style sheet로, 본 프로젝트에는 개발 편의성을 위해 포함되어 있으나 수정하지 않으려고 합니다.

이 웹폰트의 https 링크는 https://github.com/rishubil/jsassist-open-dccon/blob/44e02097e1bfe3e983322754e2ed71a7edb6b6c3/source/src/components/chat/Chat.vue#L270-L275 에 따로 재정의했으므로, 폰트 자체는 문제없이 로딩됩니다.
