### ISSUE TITLE
설정대로 진행해도 채팅이 안되는 문제

### ISSUE THREAD

**Issue by skotlex** [rishubil/jsassist-open-dccon#33]
간략하게나마 설정과정을 영상으로 찍어보았습니다
https://youtu.be/U6qrSuC7_D4

**Comment by rishubil** [comment]
JsAssist Open Dccon이 아닌 JsAssist의 기본 채팅창은 브라우저 소스에 입력하면 OBS에 표시되나요?

JsAssist의 기본 채팅창이 정상적으로 표시되지 않는다면, JsAssist의 설정 문제일 가능성이 큽니다.

만약 JsAssist의 기본 채팅창이 정상적으로 표시된다면, JsAssist Open Dccon의 채팅 소스에서 JsAssist의 채팅 데이터를 정상적으로 불러오지 못하는 것 같습니다.
이 경우에는 사용하시는 웹 브라우저(아마도 네이버 웨일 브라우저이신 것 같네요)에서 JsAssist Open Dccon 채팅 소스 주소를 직접 열어서 확인해봐야 할 것 같습니다.
아래 과정을 진행한 결과를 말씀해주세요.

1. JsAssist를 실행한 후 기본 설정을 완료합니다.
1. https://rishubil.github.io/jsassist-open-dccon/#/chat?dccon_list=https://rishubil.github.io/jsassist-open-dccon/static/dccon_list.json 페이지를 웨일 브라우저에서 접속합니다.
1. `F12`를 눌러 웨일 브라우저의 개발자 도구를 띄웁니다.
1. 개발자 도구 하단의 `Console` 탭을 클릭합니다.
1. 그대로 페이지를 새로고침하여 Console의 내용을 확인합니다.
1. Console의 내용 중 빈곳을 우클릭하여 콘솔 출력 내용을 저장합니다.
1. 저장된 Console 출력 파일을 업로드하거나, 텍스트 편집기로 열어 내용을 복사하여 이 이슈에 댓글로 달아주세요.

**Comment by skotlex** [comment]
안녕하세요
해당 이슈는 다른장소에서 동일하게 세팅하던 중 문제의 원인을 파악했습니다

이는 채팅위젯설정에서 프리셋 이름 중 default 를 삭제한 것이 원인이었습니다
default 를 프리셋으로 추가하니 웹페이지에서도 정상적으로 출력되는걸 확인했습니다
*저 같은 사람이 또 있을지도 모르니 사용방법에는 해당 부분을 주의사항쯤으로 명시해놓는 것이 좋을 것 같습니다

그리고 이건 건의사항인데 제 경우 방송하는 게임별로 채팅창 크기가 상이하여 채팅창을 2개로 사용 중입니다
혹시 채팅창을 여러개 사용하는 유저들을 위해 채팅 페이지 주소에 파라미터로 jsassist 프리셋 이름을 추가해 주실 수 있는지 문의 드립니다
ex.
https://rishubil.github.io/jsassist-open-dccon/#/chat?dccon_list=https://rishubil.github.io/jsassist-open-dccon/static/dccon_list.json&preset=[JSAssist 프리셋 이름]

덕분에 좋은 프로그램을 사용할 수 있게되어 감사말씀 드립니다

**Comment by rishubil** [comment]
잘 해결되셨다니 다행입니다.
프리셋 관련 세팅은 확인 후 적용할 수 있도록 해보겠습니다.

**Comment by rishubil** [comment]
#36 에서 jsassist 프리셋 관련 기능에 대해서 논의하고, 원래 문의 내용은 종료되었으므로 본 이슈를 닫습니다.
